name: chatgpt

version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.1
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.7
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/chatgpt_logo.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/chatgpt_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: DINNEXT
      fonts:
        - asset: assets/fonts/din-next/DINNEXT-Black.ttf
          weight: 900
        - asset: assets/fonts/din-next/DINNEXT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/din-next/DINNEXT-Bold.ttf
          weight: 700
        - asset: assets/fonts/din-next/DINNEXT-Regular.ttf
          weight: 400
        - asset: assets/fonts/din-next/DINNEXT-Light.ttf
          weight: 300
        - asset: assets/fonts/din-next/DINNEXT-UltraLight.ttf
          weight: 100
